export const categories = [
  {
    id: "animals",
    name: "בעלי חיים",
    emoji: "🐾",
    items: [
      { id: "animals_1",  name: "כלב" },
      { id: "animals_2",  name: "חתול" },
      { id: "animals_3",  name: "אריה" },
      { id: "animals_4",  name: "פיל" },
      { id: "animals_5",  name: "קוף" },
      { id: "animals_6",  name: "נחש" },
      { id: "animals_7",  name: "דולפין" },
      { id: "animals_8",  name: "פרה" },
      { id: "animals_9",  name: "סוס" },
      { id: "animals_10", name: "תוכי" },
      { id: "animals_11", name: "דב" },
      { id: "animals_12", name: "זברה" },
      { id: "animals_13", name: "כריש" },
      { id: "animals_14", name: "ינשוף" },
      { id: "animals_15", name: "קיפוד" },
    ],
  },
  {
    id: "professions",
    name: "מקצועות",
    emoji: "💼",
    items: [
      { id: "professions_1",  name: "רופא" },
      { id: "professions_2",  name: "מורה" },
      { id: "professions_3",  name: "טבח" },
      { id: "professions_4",  name: "עורך דין" },
      { id: "professions_5",  name: "שוטר" },
      { id: "professions_6",  name: "כבאי" },
      { id: "professions_7",  name: "טייס" },
      { id: "professions_8",  name: "רופא שיניים" },
      { id: "professions_9",  name: "אדריכל" },
      { id: "professions_10", name: "מהנדס" },
      { id: "professions_11", name: "שחקן" },
      { id: "professions_12", name: "זמר" },
      { id: "professions_13", name: "עיתונאי" },
      { id: "professions_14", name: "ספר" },
      { id: "professions_15", name: "נהג" },
    ],
  },
  {
    id: "countries",
    name: "מדינות",
    emoji: "🌍",
    items: [
      { id: "countries_1",  name: "ישראל" },
      { id: "countries_2",  name: "ארצות הברית" },
      { id: "countries_3",  name: "צרפת" },
      { id: "countries_4",  name: "יפן" },
      { id: "countries_5",  name: "ברזיל" },
      { id: "countries_6",  name: "אוסטרליה" },
      { id: "countries_7",  name: "גרמניה" },
      { id: "countries_8",  name: "הודו" },
      { id: "countries_9",  name: "איטליה" },
      { id: "countries_10", name: "רוסיה" },
      { id: "countries_11", name: "סין" },
      { id: "countries_12", name: "מצרים" },
      { id: "countries_13", name: "קנדה" },
      { id: "countries_14", name: "ספרד" },
      { id: "countries_15", name: "מקסיקו" },
    ],
  },
  {
    id: "foods",
    name: "אוכל",
    emoji: "🍽️",
    items: [
      { id: "foods_1",  name: "פיצה" },
      { id: "foods_2",  name: "המבורגר" },
      { id: "foods_3",  name: "סושי" },
      { id: "foods_4",  name: "פלאפל" },
      { id: "foods_5",  name: "חומוס" },
      { id: "foods_6",  name: "שווארמה" },
      { id: "foods_7",  name: "פסטה" },
      { id: "foods_8",  name: "סלט" },
      { id: "foods_9",  name: "גלידה" },
      { id: "foods_10", name: "עוגה" },
      { id: "foods_11", name: "שוקולד" },
      { id: "foods_12", name: "סביח" },
      { id: "foods_13", name: "בורקס" },
      { id: "foods_14", name: "לחם" },
      { id: "foods_15", name: "ביצים" },
    ],
  },
  {
    id: "sports",
    name: "ספורט",
    emoji: "⚽",
    items: [
      { id: "sports_1",  name: "כדורגל" },
      { id: "sports_2",  name: "כדורסל" },
      { id: "sports_3",  name: "טניס" },
      { id: "sports_4",  name: "שחייה" },
      { id: "sports_5",  name: "אופניים" },
      { id: "sports_6",  name: "גלישה" },
      { id: "sports_7",  name: "אתלטיקה" },
      { id: "sports_8",  name: "התעמלות" },
      { id: "sports_9",  name: "כדורעף" },
      { id: "sports_10", name: "קראטה" },
      { id: "sports_11", name: "שחמט" },
      { id: "sports_12", name: "רכיבה על סוסים" },
      { id: "sports_13", name: "בוקס" },
      { id: "sports_14", name: "טניס שולחן" },
      { id: "sports_15", name: "כדור מים" },
    ],
  },
];

export function getCategoryById(id) {
  return categories.find(c => c.id === id) || null;
}
